In [1]:
import numpy as np
import scipy.stats as sts
import matplotlib.pyplot as plt
import scipy.special as scp

In [2]:
f = open('IB_statistics_data_hw4.txt', 'r')
line_1 = f.readline()
list_ex = line_1.split(' ')
list_ex

['Ex3.a',
 'Ex3.b',
 'Ex3.c',
 'Ex4.a',
 'Ex4.b',
 'Ex4.c',
 'Ex4.d',
 'Ex5',
 'Ex6',
 'Ex7',
 'Ex8',
 'Ex9',
 'Ex10',
 'Ex11\n']

In [3]:
list_ex[12]

'Ex10'

In [4]:
data = [[] for x in range(len(list_ex))]
data

[[], [], [], [], [], [], [], [], [], [], [], [], [], []]

In [5]:
for line in f:
    res = line.split(' ')
    for i in range(len(res)):
        data[i].append(res[i])

In [6]:
for i in range(len(data)):
    for j in range(len(data[0])):
        data[i][j] = float(data[i][j])

### Analyzing

In [59]:
#Ex_3a
arr_1 = data[0]
arr_1 = np.array(arr_1)

In [60]:
x_mean = arr_1.mean()
n = len(arr_1)
s2 = 2

In [61]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = x_mean - s2*g_2/np.sqrt(n)
interval_2 = x_mean - s2*g_1/np.sqrt(n)

print(interval_1, interval_2)

106.9000035144675 107.07448121254905


In [11]:
#Ex_3b

In [14]:
arr_2 = data[1]
arr_2 = np.array(arr_2)
print(arr_2)

[7.243586   7.1515776  7.28386366 ... 7.19718452 7.35796134 7.69683523]


In [17]:
arr_2.std()

0.79968174859156

In [18]:
x_mean = 7.5
n = len(arr_2)
s = 0
for i in range(n):
    s += (arr_2[i]-x_mean)**2

In [20]:
g_1 = sts.chi2.ppf(0.025, n)
g_2 = sts.chi2.ppf(0.975, n)

interval_1 = np.sqrt(s/g_2)
interval_2 = np.sqrt(s/g_1)

print(interval_1, interval_2)

0.7758281731618566 0.8252061724809142


In [7]:
#Ex_3c

In [21]:
arr_3 = data[2]
arr_3 = np.array(arr_3)
print(arr_3)

[ -7.47739956 -11.47674591  -7.75843695 ...   2.24934428   4.58291782
 -19.84643869]


In [26]:
x_mean = arr_3.mean()
n = len(arr_3)
s = arr_3.std()**2

print(x_mean)

-1.2855062014893934


In [25]:
g_1 = sts.chi2.ppf(0.025, n-1)
g_2 = sts.chi2.ppf(0.975, n-1)

interval_1 = n*s/g_2
interval_2 = n*s/g_1

print(interval_1, interval_2)

466.71268714017623 528.0277335709055


In [93]:
g_1 = sts.t.ppf(0.025, n-1)
g_2 = sts.t.ppf(0.975, n-1)

interval_1 = x_mean - np.sqrt(s)*g_2/np.sqrt(n)
interval_2 = x_mean - np.sqrt(s)*g_1/np.sqrt(n)

print(interval_1, interval_2)

-2.2572458517206377 -0.3137665512581489


In [96]:
#Ex_4a

In [103]:
arr_4 = data[3]
arr_4 = np.array(arr_4)
print(arr_4)

[0. 0. 0. ... 0. 1. 0.]


In [104]:
x_mean = arr_4.mean()
n = len(arr_4)
s = arr_4.std()**2
print(x_mean)

0.4343734522040614


In [109]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = x_mean - np.sqrt(x_mean*(1-x_mean)/n)*g_2
interval_2 = x_mean - np.sqrt(x_mean*(1-x_mean)/n)*g_1

print(interval_1, interval_2)

0.4127524181285717 0.4559944862795512


In [110]:
#Ex_4б

In [111]:
arr_5 = data[4]
arr_5 = np.array(arr_5)
print(arr_5)

[57. 73. 60. ... 60. 72. 60.]


In [112]:
x_mean = arr_5.mean()
n = len(arr_5)
s = arr_5.std()**2
print(x_mean)

61.83605745418524


In [113]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = x_mean - np.sqrt(x_mean/n)*g_2
interval_2 = x_mean - np.sqrt(x_mean/n)*g_1

print(interval_1, interval_2)

61.49305215663466 62.17906275173581


In [110]:
#Ex_4c

In [117]:
arr_6 = data[5]
arr_6 = np.array(arr_6)
print(arr_6)

[12. 11. 18. ... 14. 15. 13.]


In [119]:
x_mean = arr_6.mean()
p = 0.07
n = len(arr_6)
s = arr_6.std()**2
print(x_mean/0.07)

204.26661006155805


In [120]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = x_mean/p - g_2*np.sqrt((1-p)*x_mean/n)
interval_2 = x_mean/p - g_1*np.sqrt((1-p)*x_mean/n)

print(interval_1, interval_2)

204.10754708081348 204.42567304230263


In [110]:
#Ex_4d

In [121]:
arr_7 = data[6]
arr_7 = np.array(arr_7)
print(arr_7)

[2. 0. 4. ... 0. 4. 7.]


In [129]:
x_mean = arr_7.mean()
n = len(arr_7)
s = arr_7.std()
p = 1/(x_mean+1)
print(p, s, n)

0.13824032865457034 6.631892576097748 2019


In [130]:
sigma = np.sqrt((1-p)/p**2)
print(sigma)

6.7151903136286935


In [133]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = p - g_2*sigma/np.sqrt(n)
interval_2 = p - g_1*sigma/np.sqrt(n)

print(interval_1, interval_2)

interval_1_s = p - g_2*s/np.sqrt(n)
interval_2_s = p - g_1*s/np.sqrt(n)

print(interval_1_s, interval_2_s)

-0.15467240837080345 0.43115306567994416
-0.15103900899585318 0.42751966630499394


In [110]:
#Ex_5

In [135]:
arr_8 = data[7]
arr_8 = np.array(arr_8)
print(arr_8)

[18.65438377 12.50788801  3.23764216 ...  6.78423938 23.95790747
  4.47192804]


In [144]:
x_mean = arr_8.mean()
n = len(arr_8)
s = arr_8.std()
sigma = 0
for x in arr_8:
    sigma += x**2
sigma = np.sqrt(sigma/(2*n))
print(x_mean, s, n, np.sqrt(np.pi/2)*sigma, sigma)

9.898842915146215 5.211438114066591 2019 9.914110074725649 7.910315362723737


In [142]:
std = np.sqrt((2-np.pi/2)*sigma**2)
print(std)

5.182335352108133


In [145]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = sigma - g_2*std/np.sqrt(n)
interval_2 = sigma - g_1*std/np.sqrt(n)

print(interval_1, interval_2)

interval_1_s = sigma - g_2*s/np.sqrt(n)
interval_2_s = sigma - g_1*s/np.sqrt(n)

print(interval_1_s, interval_2_s)

7.6842648769931134 8.13636584845436
7.682995431264532 8.137635294182942


In [110]:
#Ex_6

In [24]:
arr_9 = data[8]
arr_9 = np.array(arr_9)
print(arr_9)

[25. 30. 19. ... 23. 29. 25.]


In [25]:
x_mean = arr_9.mean()
n = len(arr_9)
s = arr_9.std()

print(x_mean, s, n)

26.490341753343237 4.196543405568954 2019


In [29]:
p = (x_mean - s**2)/x_mean
m = (x_mean)**2/(x_mean-s**2)
print(p, m)

std = np.sqrt(p*(1-p)*m)

0.33519254984312674 79.0302223773797


In [30]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = p - g_2*std/np.sqrt(n)
interval_2 = p - g_1*std/np.sqrt(n)

print(interval_1, interval_2)

interval_1_s = m - g_2*std/np.sqrt(n)
interval_2_s = m - g_1*std/np.sqrt(n)

print(interval_1_s, interval_2_s)

0.1521417415173758 0.5182433581688778
78.84717156905396 79.21327318570545


In [110]:
#Ex_7

In [162]:
arr_10 = data[9]
arr_10 = np.array(arr_10)
print(arr_10[343])

8.0


In [163]:
x_mean = arr_10.mean()
n = len(arr_10)
s = arr_10.std()

print(x_mean, s, n)

1.9712729073798911 1.323078536813121 2019


In [171]:
from scipy.optimize import fsolve

def equation(theta):
    return (np.log((2*p-1)/p))/np.log(p) - theta

p = fsolve(equation, 8)
p

array([0.30229687])

In [177]:
s = 0
for i in range(1, 9):
    s += i*0.39**i
p = 0.385

1.044806979941915

In [179]:
s**8

1.4200005818015502

In [183]:
print((1-p**8)**2019)

[0.86865797]


In [145]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = sigma - g_2*std/np.sqrt(n)
interval_2 = sigma - g_1*std/np.sqrt(n)

print(interval_1, interval_2)

interval_1_s = sigma - g_2*s/np.sqrt(n)
interval_2_s = sigma - g_1*s/np.sqrt(n)

print(interval_1_s, interval_2_s)

7.6842648769931134 8.13636584845436
7.682995431264532 8.137635294182942


In [ ]:
#Ex_10

In [15]:
arr_13 = data[12]
arr_13 = np.array(arr_13)
print(arr_13)

[-2.06511097  1.24962602 -2.14357806 ... -2.35538587 -5.28481821
 -1.82061961]


In [16]:
x_mean = arr_13.mean()
n = len(arr_13)
s = arr_13.std()**2

print(s**0.5, x_mean)

1.7438903429367514 -2.975087198298646


In [23]:
from scipy.optimize import fsolve

g_1 = sts.chi2.ppf(0.025, n)
g_2 = sts.chi2.ppf(0.975, n)

summ_2 = 0
for x in arr_13:
    summ_2 += x**2
summ_2 = summ_2/n

def equation(theta,):
    return n*summ_2 - n*2*x_mean*theta + (n-g_1)*theta**2

sigma = fsolve(equation, -3)
sigma

array([-2.04118065])

In [45]:
#Ex 8

In [7]:
arr_11 = data[10]
arr_11 = np.array(arr_11)
print(arr_11)

[0.0505231  0.07706069 0.         ... 0.29414683 0.         0.25365367]


In [8]:
x_mean = arr_11.mean()
n = len(arr_11)
s = arr_11.std()

print(x_mean, s, n)

0.045699357257548444 0.08463340522184624 2019


In [11]:
sigma = 1 - np.sqrt(2*x_mean)
h = np.argmax(arr_11)
h = arr_11[h]
print(sigma, h)

0.6976777968539246 0.299312368431129


In [14]:
g_1 = sts.norm.ppf(0.025)
g_2 = sts.norm.ppf(0.975)

interval_1 = 1-np.sqrt((x_mean - g_2*x_mean**(3/2)/np.sqrt(18*n))*2)
interval_2 = 1-np.sqrt((x_mean - g_1*x_mean**(3/2)/np.sqrt(18*n))*2)

print(interval_1, interval_2)

0.698010209547075 0.6973457492576847


In [13]:
(1-sigma)**2/2

0.04569935725754844